---
- hosts: localhost
  tasks:
    - name: First time setup of a unity array
      dellemc_unity:
        unity_hostname: "192.168.0.34"
        unity_username: admin
        unity_password: Password#1
        unity_dns_servers:
          - 192.168.0.10
        unity_syslog_enabled: True
        unity_syslog_server: "192.168.0.11:515"
        unity_syslog_loglevel: 0
        unity_syslog_protocol: 1
      register: result
    - debug: var=result
