---
- hosts: localhost
  tasks:
    - name: Pool Creation and Updates
      dellemc_unity:
        unity_hostname: "10.245.16.171"
        unity_username: admin
        unity_password: Password123!
        unity_updates:
          - {resource_type: pool, action: 'recommendAutoConfiguration'}
          # - {resource_type: pool, name: 'performancePool', 'addRaidGroupParameters': [{"dskGroup" : {"id" : "dg_3"}, "numDisks" : 6, "raidType" : 48879, "stripeWidth" : 0}]}
          # - {resource_type: pool, id: pool_1, name: 'highPerformancePool', description: 'high performance pool'}
      register: result
    - debug: var=result
