---
- hosts: localhost
  tasks:
    - name: get disks
      virtualDisk:
       login:
          host: "{{ host }}"
          username: "{{ username }}"
          password: "{{ password }}"
       get:
         fields: id
      register: get_disks_results
    - debug: var=get_disks_results['output']['get']

    - name: Create pool
      pool:
        login:
          host: "{{ host }}"
          username: "{{ username }}"
          password: "{{ password }}"
        createVSA:
          name: test_pool
          addPoolUnitParameters: [{"poolUnit" : {"id" : "vdisk_1"}}, {"poolUnit" : {"id" : "vdisk_2"}}] #["poolUnit": "{{ get_disks_results['output']['get'][0] }}", "poolUnit": "{{ get_disks_results['output']['get'][1] }}"]
      register: create_pool_results
    - debug: var=create_pool_results

    - name: create Nas Server
      nasServer:
         login:
           host: "{{ host }}"
           username: "{{ username }}"
           password: "{{ password }}"
         create:
           name: nasServerFromPlaybook
           homeSP: {id: 'spa'}
           pool:  {id: "{{ create_pool_results['output']['createVSA']['id'] }}"}
           isMultiProtocolEnabled: false
      register: create_nas_server_results
    - debug: var=create_nas_server_results

    - name: nfsServer creation
      nfsServer:
        login:
          host: "{{ host }}"
          username: "{{ username }}"
          password: "{{ password }}"
        create:
          nasServer: {id: "{{ create_nas_server_results['output']['create']['id'] }}"}
      register: result

    - name: create fileInterface
      fileInterface:
        login:
          host: "{{ host }}"
          username: "{{ username }}"
          password: "{{ password }}"
        create:
          nasServer: {id: "{{ create_nas_server_results['output']['create']['id'] }}"}
          ipPort: {id: "spa_eth0"}
          ipAddress: "{{ fileInterface_ip }}"
      register: file_interface_create_results
    - debug: var=file_interface_create_results

    - name: create file system
      filesystem:
        login:
          host: "{{ host }}"
          username: "{{ username }}"
          password: "{{ password }}"
        create:
          name: file_system_created_by_playbook
          fsParameters:
            pool:  {id: "{{ create_pool_results['output']['createVSA']['id'] }}"}
            nasServer: {id: "{{ create_nas_server_results['output']['create']['id'] }}"}
            size: 5368709120 # size 5 GB
            supportedProtocols: 0
      register: file_system_create_results
    - debug: var=file_system_create_results

    - name: get storageResource id from file system
      filesystem:
        login:
          host: "{{ host }}"
          username: "{{ username }}"
          password: "{{ password }}"
        get:
          id: "{{ file_system_create_results['output']['create']['id'] }}"
          fields: storageResource
      register: result
    - debug: var=result['output']

    - name: create nfsShare
      nfsShare:
        login:
          host: "{{ host }}"
          username: "{{ username }}"
          password: "{{ password }}"
        create:
          storageResourceId: {'id': "{{ result['output']['get']['storageResource']['id'] }}"}
          name: nfsShareTestPlaybook
          path: '/'
      register: result1
    - debug: var=result1
