---
- hosts: localhost
  vars_files:
    - ../../group_vars/all
  tasks:
    - name: get nasServer id
      commonGetPost:
        login:
          unityIP: "{{ unity_ip_source }}"
          username: "{{ unity_username }}"
          password: "{{ unity_password }}"
        get:
          resource_type: nasServer
          fields: id
      register: result1
    - debug: var=result1['output']

    - name: Create fileInterface
      fileInterface:
        login:
          unityIP: "{{ unity_ip_source }}"
          username: "{{ unity_username }}"
          password: "{{ unity_password }}"
        create:
          nasServer: {id: "{{ result1['output']['get'][0]['id'] }}"}
          ipPort: {id: "{{ fileInterface_ipPort }}"}
          ipAddress: "{{ fileInterface_ipAddress }}"
      register: result2
    - debug: var=result2['output']