---
- host: localhost
  vars_files:
    - ../../group_vars/all
  tasks:
    - name: Get fileInterface_id
      commonGetPost:
        login:
          unityIP: "{{ unity_ip_source }}"
          username: "{{ unity_username }}"
          password: "{{ unity_password }}"
        get:
          resource_type: fileInterface
          fields: id  
      register: result1
    - debug: var=result1['output']

    - name: Delete fileInterface
      fileInterface:
        login:
          unityIP: "{{ unity_ip_source }}"
          username: "{{ unity_username }}"
          password: "{{ unity_password }}"
        delete:
          id: "{{ result1['output']['get'][0]['id'] }}"
      register: result1
    - debug: var=result1['output']
