---
- hosts: localhost
  vars_files:
    - ../../group_vars/all
  tasks:
    - name: get
      commonGetPost:
        login:
          unityIP: "{{ unity_host }}"
          username: "{{ unity_username }}"
          password: "{{ unity_password }}"
        get:
          resource_type: ipPort
          fields: id
      register: result1
    - debug: var=result1['output']