---
- hosts: localhost
  vars_files:
    - ../../group_vars/all
  tasks:
    #a simple example of a get request
    - name: get
      commonGetPost:
        login:
          unityIP: "{{ unity_ip_source }}"
          username: "{{ unity_username }}"
          password: "{{ unity_password }}"
        get:
          resource_type: filesystem
          fields: storageResource
      register: result1
    - debug: var=result1['output']
