---
- hosts: localhost
  vars_files:
    - ../../group_vars/all
  tasks:
    - name: Create nfsServer
      nfsServer:
        login:
          host: "{{ unity_host }}"
          username: "{{ unity_username }}"
          password: "{{ unity_password }}"
        create:
          nasServer: {'id': "{{ nasServer_id }}"}
      register: result1
    - debug: var=result1['output']
