---
- hosts: localhost
  vars_files:
    - ../../group_vars/all
  tasks:
    - name: Get nfsServer
      nfsServer:
        login:
          unityIP: "{{ unity_host }}"
          username: "{{ unity_username }}"
          password: "{{ unity_password }}"
        get:
          fields: id
      register: result1
    - debug: var=result1['output']['get'][0]['id']

    - name: Delete nfsServer
      nfsServer:
        login:
          unityIP: "{{ unity_host }}"
          username: "{{ unity_username }}"
          password: "{{ unity_password }}"
        delete:
          id: "{{ result1['output']['get'][0]['id'] }}"
      register: result2
    - debug: var=result2['output']
