---
- hosts: localhost
  vars_files:
    - ../../group_vars/all
  tasks:
    - name: Create filesystem
      commonGetPost:
        login:
          host: "{{ unity_host }}"
          username: "{{ unity_username }}"
          password: "{{ unity_password }}"
        get:
          resource_type: nfsShare
          fields: id
      register: result1
    - debug: var=result1['output']['get'][0]['id']
    - name: Create nfsShare
      nfsShare:
        login:
          host: "{{ unity_host }}"
          username: "{{ unity_username }}"
          password: "{{ unity_password }}"
        delete:
          storageResourceId: res_4
          id: "{{ result1['output']['get'][0]['id'] }}"
      register: result2
    - debug: var=result2
