---
- hosts: localhost
  vars_files:
    - ../../group_vars/all
  tasks:
    - name: Delete pool
      pool:
        login:
          unityIP: "{{ unity_host }}"
          username: "{{ unity_username }}"
          password: "{{ unity_password }}"
        delete:
          id: "{{ pool_id }}"

      register: result1
    - debug: var=result1['output']
