---
- hosts: localhost
  vars_files:
    - ../../group_vars/all
  tasks:
    - name: Modify pool
      pool:
        login:
          host: "{{ unity_host }}"
          username: "{{ unity_username }}"
          password: "{{ unity_password }}"
        modify:
          id: "{{ pool_id }}"
          name: "modifyNameByPlaybook"

      register: result1
    - debug: var=result1['output']
