---
- hosts: localhost
  vars_files:
    - ../../group_vars/all
  tasks:
    - name: create remoteSystem
      remoteSystem:
        login:
          unityIP: "{{ unity_ip_source }}"
          username: "{{ unity_username }}"
          password: "{{ unity_password }}"
        create:
          #all of the further parameters are required. DellEMC documentation lies:)
          managementAddress: "{{ unity_ip_dest }}"
          remoteUsername: "{{ unity_username }}"
          remotePassword: "{{ unity_password }}"
          localUsername: "{{ unity_username }}"
          localPassword: "{{ unity_password }}"
      register: create_remoteSystem
    - debug: var=create_remoteSystem['output']