---
- hosts: localhost
  tasks:
    - name: pool creation
      pool:
        login:
          host: "{{ host }}"
          username: "{{ username }}"
          password: "{{ password }}"
        create:
          name: PoolByPlaybook
          addPoolUnitParameters: [{"poolUnit" : {"id" : "vdisk_1"}}, {"poolUnit" : {"id" : "vdisk_2"}}]
      register: pool_result
    - debug: var=pool_result

    - name: lun creation
      lun:
        login:
          host: "{{ host }}"
          username: "{{ username }}"
          password: "{{ password }}"
        createLun:
          name: lunByPlaybook
          lunParameters: {pool: {id: "{{ pool_result['output']['create']['id'] }}"}, "size": 1073741824}
      register: lun_result
    - debug: var=lun_result

    - name: host creation
      host:
        login:
          host: "{{ host }}"
          username: "{{ username }}"
          password: "{{ password }}"
        create:
          type: 1
          name: "hostByPlaybook"
      register: host_result
    - debug: var=host_result

    - name: lun modify
      lun:
        login:
          host: "{{ host }}"
          username: "{{ username }}"
          password: "{{ password }}"
        modifyLun:
          id: "{{ lun_result['output']['createLun']['storageResource']['id'] }}"
          lunParameters: { "hostAccess" : [{"host": {"id": "{{ host_result['output']['create']['id'] }}"}, "accessMask": 3}] }
      register: result_modify_lun
    - debug: var=result_modify_lun

    - name: portal create
      portal:
        login:
          host: "{{ host }}"
          username: "{{ username }}"
          password: "{{ password }}"
        create:
          ethernetPort: {"id": "spa_eth0"}
          ipAddress: "192.168.70.217"
          netmask: "255.255.255.0"
      register: result
    - debug: var=result
