---
- hosts: localhost
  tasks:
    - name: fileInterface creation
      fileInterface:
        login:
          host: 192.168.70.217
          username: admin
          password: Password123!
        create:
          nasServer: {id: "nas_7"}
          ipPort: {id: "spa_eth0"}
          ipAddress: 192.168.70.226
      register: result
    - debug: var=result