---
- hosts: localhost
  tasks:
    - name: get pool id
      nfsServer:
        login:
          host: 192.168.70.218
          username: admin
          password: Password123!
        get:
          fields: id
      register: result
    - debug: var=result

