---
- hosts: localhost
  tasks:
    - name: lun create
      initiator:
        login:
          #host: "{{ host }}"
          #username: "{{ username }}"
          #password: "{{ password }}"
          host: 192.168.70.218
          username: admin
          password: Password123!
        create:
          host: Host_31
          initiatorType: 2
          initiatorWWNorIqn: 
      register: result
    - debug: var=result
