---
- hosts: localhost
  tasks:
    - name: Create nasServer
      nasServer:
         login:
           host: "{{ host }}"
           username: "{{ username }}"
           password: "{{ password }}"
         create:
           name: nasServerFromPlaybook
           homeSP: {id: 'spa'}
           pool:  {id: "pool_41"}
           isMultiProtocolEnabled: false
      register: create_nas_server_results
    - debug: var=create_nas_server_results

