---
- hosts: localhost
  tasks:
    - name: get id
      commonGetPost:
        login:
          host: 192.168.70.217
          username: admin
          password: Password123!
        get:
          resource_type: filesystem
          fields: storageResource
      register: result
    - debug: var=result['output']['get'][0]['storageResource']['id']

    - name: nfsShare creation
      nfsShare:
        login:
          host: 192.168.70.217
          username: admin
          password: Password123!
        create:
          storageResourceId: {'id': "{{ result['output']['get'][0]['storageResource']['id'] }}"}
          name: nfsShareTestPlaybook
          path: '/'
      register: result1
    - debug: var=result1['output']
 

