---
- hosts: localhost
  tasks:
    - name: get nasServer
      nasServer:
        login:
          host: 192.168.70.218
          username: admin
          password: Password123!
        get:
          fields: id
      register: result1
    - debug: var=result1['output']['get'][0]['id']  
    - name: nfsServer creation
      nfsServer:
        login:
          host: 192.168.70.218
          username: admin
          password: Password123!
        create:
          nasServer: {'id': "{{ result1['output']['get'][0]['id'] }}"}
      register: result2
    - debug: var=result2['output']['create']['id']
