---
- hosts: localhost
  tasks:
    - name: filesystem creation
      storageResource:
        login:
          host: 192.168.70.218
          username: admin
          password: Password123!
        get:
          fields: id
      register: result
    - debug: var=result
    #['output']['get'][0]['id']
    - name: nfsShare creation
      nfsShare:
        login:
          host: 192.168.70.218
          username: admin
          password: Password123!
        create:
          storageResourceId: {'id': 'res_4'}
          name: nfsShareTestPlaybook
          path: '/'
      register: result1
    - debug: var=result1
 

