---
- hosts: localhost
  tasks:
    - name: nfsServer creation
      nfsServer:
        login:
          host: "{{ host2 }}"
          username: "{{ username }}"
          password: "{{ password }}"
        create:
          nasServer: {'id': 'nas_4'}
      register: result
    - debug: var=result['special_information']['create']