---
- hosts: localhost
  tasks:
    - name: create iscsiPortal
      dellemc_unity:
        unity_hostname: 192.168.70.217
        unity_username: admin
        unity_password: Password123!
        create_iscsiPortal:
          - "ethernetPort": {"id": "spa_eth2"}
            "ipAddress": "192.168.70.218"
            "netmask": "255.255.255.0"
      register: result
    - debug: var=result