---
- hosts: localhost
  tasks:
    - name: Pool Creation and Updates
      dellemc_unity:
        unity_hostname: "192.168.70.217"
        unity_username: admin
        unity_password: Password123!
        create_pool:
          name: pool
          description: "created from module"
          pool_unit_params: [{"poolUnit" : {"id" : "vdisk_1"}}, {"poolUnit" : {"id" : "vdisk_2"}}]
      register: result
    - debug: var=result