---
- hosts: localhost
  tasks:
    - name: Create pool
      pool:
        login:
          host: "{{ address }}"
          username: admin
          password: Password123!
        create:
          name: test_pool
          addPoolUnitParameters: [{"poolUnit" : {"id" : "vdisk_1"}}, {"poolUnit" : {"id" : "vdisk_2"}}]
      register: result
    - debug: var=result['output']['create']['id']
    - name: Modify pool
      pool:
        login:
          host: "{{ address }}"
          username: admin
          password: Password123!
        modify:
          id: "{{ result['output']['create']['id'] }}"
          name: modify_name
      register: result1
    - debug: var=result1
    - name: Delete pool
      pool:
        login:
          host: "{{ address }}"
          username: admin
          password: Password123!
        delete:
          id: "{{ result['output']['create']['id'] }}"