---
- hosts: localhost
  tasks:
    - name: Modify pool
      pool:
        login:
          host: "{{ address }}"
          username: admin
          password: Password123!
        modifyVSA:
          id: pool_27
          name: modify_name
      register: result1
    - debug: var=result1
