---
- hosts: localhost
  tasks:
    - name: Pool Creation and Updates
      pool:
        login:
          host: 192.168.70.217
          username: admin
          password: Password123!
        create:
          name: swimmingPool
          addPoolUnitParameters: [{"poolUnit" : {"id" : "vdisk_1"}}, {"poolUnit" : {"id" : "vdisk_2"}}]
      register: result
    - debug: var=result
