---
- hosts: localhost
  tasks:
    - name: Pool Creation and Updates
      pool:
        login:
          host: "{{ host }}"
          username: "{{ username }}"
          password: "{{ password }}"
        create:
          name: swimmingPool
          addPoolUnitParameters: [{"poolUnit" : {"id" : "vdisk_1"}}, {"poolUnit" : {"id" : "vdisk_2"}}]
      register: result
    - debug: var=result